name: Natural Random Activity

on:
  schedule:
    # Berjalan setiap jam dari jam 07:00 sampai 22:00 WIB (Jam sibuk manusia)
    # Ini memberikan 15 kesempatan bagi skrip untuk memilih waktu acaknya
    - cron: '0 0-15 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Script
        # Tambahkan '|| exit 0' agar jika skrip sys.exit(1), action tidak dianggap gagal (tetap hijau)
        run: python auto_git_cloud.py || exit 0

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: daily system sync"
          file_pattern: activity_log.md
          # Action ini hanya akan melakukan push JIKA ada perubahan pada file
